### ISSUE TITLE
Add random_state and allow using StratifiedKFold

### ISSUE THREAD

**Issue by iajst17** [casperbh96/Nested-Cross-Validation#11]
Hi Casper, 

Thank you so much for your program. I suggest to add random_state to reproduce the results and allow StratifiedKFold option as well.

Kind regards,

Ken

**Comment by casper-hansen** [comment]
This issue is linked to #7 

I'm working on it now, but it might not be released until there are more features added

**Comment by casper-hansen** [comment]
This is now a feature.

But it is not released, so pull the github package with pip like this:

`pip install git+https://github.com/casperbh96/Nested-Cross-Validation.git`

**Comment by iajst17** [comment]
Thank you. Hope to see your new version of NestedCV soon.
